//DOM (API):interface between our code and the browser (HTML documents rendered in by the browser)
// => make js interact with the browser
//DOM tree is generated from any HTML document
//made of Nodes.
//Interface Contains lots of methods and properties to interact with the DOM tree
//different types of nodes : Html element=s vs text ...
//Nodes type : Element , Text , Comment , Document
//Element is the Parent of HTMLElement
//one different type of HTMLElement per html element : div ...
//because each html element may have its own unique properties (href , src ..)
//All of this is implemented using Inheritance
//document that we use is another type of node
//all nodes should be able to listen to events
//EventTarget(Abstract Type) : parent of both Node and Window(global object)
// => has the methods addEventListener() and removeEventListener

//Selecting,Creating and Deleting Elements

//1-Select
document.documentElement; // the entire HTML document : root node of the document
document.head; //body element
document.body; // head element
const header = document.querySelector(".header"); //first Element
document.querySelectorAll(".section"); // returns node list

// not only available for document but also elements

const firstSection = document.getElementById("section--1");

const allButtons = document.getElementsByTagName("button");
//returns an HTMLCollection
//if one element is deleted;also its deleted from HTMLCollection
//doesnt happen with node list

document.getElementsByClassName("btn");
//return HTMLCollection

// HTMLCollection is a live collection (gets updated)

//2-Creating and Inserting Elements
firstSection.insertAdjacentHTML("afterbegin", "<di>Hello</di>");

//creating an element
const message = document.createElement("div");
//not in DOM yet
message.innerText = "Hello";

// this is a unique element ;can only be inserted once
header.append(message); // insert after last child of Node
header.prepend(message); // before first last child
//the same element cant exist at 2 places
//will be moved by last action on it. (prepend)
header.prepend(message.cloneNode(true)); // true for deep copy

//also .before and .after
const cookieElement = document.createElement("div");
cookieElement.classList.add("cookie-message");
cookieElement.innerHTML = `We use cookies for improved functionality and analytics.
<button class = "btn btn--close-cookie">Got it!</button>
`;
header.append(cookieElement);

//delete element
document
  .querySelector("btn--close-cookie")
  .addEventListener("click", function () {
    cookieElement.remove(); // removes Node from DOM tree
  }); //recent method

//before remove

//styles
cookieElement.style.backgroundColor = "blue";
//will be inline style

let width = cookieElement.style.width;
//only works if we did set the width using ,style
//or if its already inline-styled

//else : use
width = getComputedStyle(cookieElement).width;
cookieElement.style.height =
  parseFloat(getComputedStyle(cookieElement).height, 10) + 40 + "px";

//Attributes
const logo = document.querySelector(".nav__logo");
logo.alt = "new text";
console.log(logo.src); // absolute :localhost...
console.getAttribute("src"); //relative
//relative : same as defined in the project

//for already absolute links (link to social media)
//doesnt matter which one we use

//store data in UI : in HTML ?
//Data attributes
`
<img src="img/user-1.jpg"
alt=""
class="testimonial__photo"
data-version-number="3.0"
/>
`;
//we can get that data from element.dataset Obejct

const logoVersionNumber = logo.dataset.versionNumber; //CamelCase
//Classes
logo.classList.add("c");
logo.classList.remove("c");
logo.classList.toggle("c");
logo.classList.contains("c");

//implement scrolling
const btnScrollTo = document.querySelector(".btn--scroll-to");
const section1 = document.querySelector("#section--1");

btnScrollTo.addEventListener("click", function (e) {
  //get coords of an elemenet relative to client screen
  //viewport:the user's visible area of a web page
  const s1coords = section1.getBoundingClientRect();
  console.log(s1coords);
  //current scroll postion (x,y)
  window.scrollX;
  window.scrollY;
  //hegiht and width of viewport
  document.documentElement.clientHeight;
  document.documentElement.clientWidth;

  //scroll x and y is not included -> we need to add these
  // window.scrollTo(
  //   s1coords.left + window.scrollX,
  //   s1coords.top + window.scrollY
  // );
  //make it smoother : pass an object
  window.scrollTo({
    left: s1coords.left + window.scrollX,
    top: s1coords.top + window.scrollY,
    behavior: "smooth",
  });

  //modern way:
  section1.scrollIntoView({ behavior: "smooth" });
});

//types of events and event Handlers
//event is a signal generated by a DOM Node (click,move ...)
//events will always be generated even if we don't handle them

const h1 = document.querySelector("h1");
//hover event
h1.addEventListener("mouseenter", function (e) {
  console.log("You are reading the heading");
}); //mostly used ; doesnt override previous eventListeners(callbacks)
//can add multiple evenetListeners to same element/event
//another way to attach an eventListener to an Element
h1.onmouseenter = function (e) {
  console.log("You are reading the heading");
}; //old school way

//remove an eventListener
//first export the function and give it name
const alertH1 = function (e) {
  console.log("You are reading the heading");
};
h1.addEventListener("mouseenter", alertH1);
//h1.removeEventListener("mouseenter", alertH1)
setTimeout(() => h1.removeEventListener("mouseenter", alertH1), 3000);

//we cant also add eventslistening directly in html elements (index.html)
//html elements attributes : onclick
`<h1 onclick="alert("!")"></h1>`;

//Event Propagation: Bubbling and Capturing
//example of click event (a element)
`
<html>
    <head>
    </head>
    <body>
        <p>
            <a onclick="alert()">link</a>
        </p>
    </body>
</html>
`;
//1- phase 1:capturing phase
//the event is generated at root to document (not target)
//the event travels from the document root to target element
//when reaches target : event can be handeled (eventListeneres)
//2- phase 2:Bubbling phase:
//the event travels up (through parents of target)
//as if the event also happenend in each of the parent eleements
//->event propagation
//3-same event can be handled many times
//by default events can be handled in the target and bubbling phase
//can make them listen in the capturing phase instead

//! not all events do have a capturing and a bubbling phase

//example
const randomInt = (min, max) =>
  Math.trunc(Math.random() * (max - min + 1)) + min;

const randomColor = () =>
  `rgb(${randomInt(0, 255)},${randomInt(0, 255)},${randomInt(0, 255)})`;
document.querySelector(".nav__link").addEventListener("click", function (e) {
  this.style.backgroundColor = randomColor();
  console.log(e.target); //were the click happened
  console.log(e.currentTarget === this); //current element
});
document.querySelector(".nav__links").addEventListener("click", function (e) {
  this.style.backgroundColor = randomColor();
  console.log(e.target); //were the click happened
  e.stopPropagation(); // stops up propagation
});
document.querySelector(".nav").addEventListener("click", function (e) {
  this.style.backgroundColor = randomColor();
  console.log(e.target); //were the click happened
});
//1)event created at root (documentElement)
//2)propagates to target (.nav_link);handled by enventListener
//3)propagates up through parents ".nav_links" and ".nav"

//for the 3 : e.target ->same (where the click happened)

//we can stop propagation : e.stopPropagation()

//to make an element listen in capturing phase:
//3rd parameter : set to true in the addEvenetListener

document.querySelector(".nav").addEventListener(
  "click",
  function (e) {
    this.style.backgroundColor = randomColor();
    console.log(e.target); //were the click happened
  },
  true
);

//Event Delegation
//Page navigation
//smooth scrolling
//1-not optimal solution
// document.querySelectorAll('.nav__link').forEach(function (el) {
//   el.addEventListener('click', function (e) {
//     e.preventDefault();
//     const id = el.getAttribute('href'); //get relative
//     const section = document.querySelector(id);
//     section.scrollIntoView({ behavior: 'smooth' });
//   });
// });
//assign the same eventHandler to differnet elements
//if many elements ->affect the performace

//use Event delegation
//listen to the event in a common parent
//when the event bubbles up to parent;catch it and handle it there
//source of event can be found in e.target
//2-using event delegation
document.querySelector(".nav__links").addEventListener("click", function (e) {
  e.preventDefault();
  const eventSource = e.target;
  if (eventSource.tagName === "A") {
    const sourceId = eventSource.getAttribute("href");
    const section = document.querySelector(sourceId);
    section.scrollIntoView({ behavior: "smooth" });
  }
});

//Another use case of event delegation
//when you add elements at run time
//can't add event listeners to elements not yet in page
//add to event to a common parent -> event delegation

//DOM traversing
const h1 = document.querySelector("h1");

//Going downwards: child
h1.querySelectorAll(".highlight");
h1.childNodes; //node list of all type of nodes (children)
h1.children; //HTMLCollection: only Elements
h1.firstElementChild; //first child
h1.lastElementChild; //last child

//going upwards: parents
h1.parentNode;
h1.parentElement; // both : direct parent

//closest parent that matches a specific selector
h1.closest(".header"); //closest parent to h1;with a class header
//if the calling element matches the selector -> returns the same element
h1.closest("h1"); // -> h1

//going sideways: siblings
//only direct siblings (previous a)
h1.previousElementSibling;
h1.nextElementSibling;
//if we need other siblings : move up the get children
[...h1.parentElement.children].forEach(function (el) {});

//building a tabbed component
const tabs = document.querySelectorAll(".operations__tab");
const tabsContainer = document.querySelector(".operations__tab-container");
const tabscontent = document.querySelectorAll(".operations__content");

//event delegation
tabsContainer.addEventListener("click", function (e) {
  e.preventDefault();

  const clicked = e.target.closest(".operations__tab");
  if (!clicked) return;
  const tabId = clicked.dataset.tab;
  tabs.forEach((tab) => tab.classList.remove("operations__tab--active"));
  clicked.classList.add("operations__tab--active");
  tabscontent.forEach((content) =>
    content.classList.remove("operations__content--active")
  );
  document
    .querySelector(`.operations__content--${tabId}`)
    .classList.add("operations__content--active");
});

//pass arguments into event handlers functions
const nav = document.querySelector(".nav");
//mouseover vs mouseenter events ;mouseover bubbles while mouseenter doesnt
//to use event delegation ->mouseover

nav.addEventListener("mouseover", function (e) {
  e.preventDefault();
  if (e.target.classList.contains("nav__link")) {
    const link = e.target;
    const siblings = link.closest(".nav__links").querySelectorAll(".nav__link");
    const logo = link.closest(".nav").querySelector("img");
    siblings.forEach((el) => {
      if (el !== link) el.style.opacity = 0.5;
    });
    logo.style.opacity = 0.5;
  }
});

//opposite
nav.addEventListener("mouseout", function (e) {
  e.preventDefault();
  if (e.target.classList.contains("nav__link")) {
    const link = e.target;
    const siblings = link.closest(".nav__links").querySelectorAll(".nav__link");
    const logo = link.closest(".nav").querySelector("img");
    siblings.forEach((el) => {
      if (el !== link) el.style.opacity = 1;
    });
    logo.style.opacity = 1;
  }
});
//repeated code
const handleHover1 = function (e, opacity) {
  e.preventDefault();
  if (e.target.classList.contains("nav__link")) {
    const link = e.target;
    const siblings = link.closest(".nav__links").querySelectorAll(".nav__link");
    const logo = link.closest(".nav").querySelector("img");
    siblings.forEach((el) => {
      if (el !== link) el.style.opacity = opacity;
    });
    logo.style.opacity = opacity;
  }
};

nav.addEventListener("mouseover", function (e) {
  handleHover1(0.5);
});
nav.addEventListener("mouseout", function (e) {
  handleHover1(1);
});

const handleHover2 = function (e) {
  e.preventDefault();
  if (e.target.classList.contains("nav__link")) {
    const link = e.target;
    const siblings = link.closest(".nav__links").querySelectorAll(".nav__link");
    const logo = link.closest(".nav").querySelector("img");
    siblings.forEach((el) => {
      if (el !== link) el.style.opacity = this;
    });
    logo.style.opacity = this;
  }
};

//using bind ; returns a function ; binds function with argument ->this

nav.addEventListener("mouseover", handleHover2.bind(0.5)); //this = 0.5
nav.addEventListener("mouseout", handleHover2.bind(1)); //this = 1

// e.currentTarget still points to current element;
//bind only change what this keyword points to;e.currentTarget!==this for this case

//Implementing a sticky Navigation: the scroll event
//this event is only available on the window object

// event as parameter is not needed here
const initialCoords = section1.getBoundingClientRect();
window.addEventListener("scroll", function () {
  if (window.scrollY > initialCoords.top) {
    nav.classList.add("sticky");
  } else {
    nav.classList.remove("sticky");
  }
});

//using scroll event is really bad for performance
//scroll event fires all the time no matter how small the scroll is

//more efficient tool : the Intersection Observer API

// const ObsCallback = function (entries,observer) {
//   console.log("called");
// };
// const obsOptions = {
//   root: null, //viewport
//   threshold: 0.5, // intersection percentage between root and observed element
//   //can pass an array of threshold
// };

// const observer = new IntersectionObserver(ObsCallback, obsOptions);
// observer.observe(section1);

//when header is no longer visible -> add sticky
const stickyNav = function (entries) {
  const [entry] = entries;
  if (!entry.isIntersecting) nav.classList.add("sticky");
  else {
    nav.classList.remove("sticky");
  }
};
const obsOptions = {
  root: null, //viewport
  threshold: 0, // intersection percentage between root and observed element
};

const headerObserver = new IntersectionObserver(stickyNav, obsOptions);
observer.observe(header);

//lazy loading images
//first load a low-quality blurred image.then load the real one when it appears in viewport
const imgTargets = document.querySelectorAll("img[data-src]");
//images with the attribute data-src (custom data-attribute)

const loadImg = function (entries, observer) {
  entries.forEach((entry) => {
    if (entry.isIntersecting) {
      const imgSrc = entry.target.dataset.src;
      entry.target.setAttribute("src", imgSrc);
      //after this line,browser will start loading the image
      //when it finished it will emit a load event; we should listen to it
      entry.target.addEventListener("load", function () {
        entry.target.classList.remove("lazy-img");
        //only when image is fully loaded remove blur effect
      });
      observer.unobserve(entry.target);
    }
  });
};
const imgObserver = new IntersectionObserver(loadImg, {
  root: null,
  threshold: 0,
  rootMargin: `200px`,
});

imgTargets.forEach((img) => imgObserver.observe(img));

//Life cycle DOM events
document.addEventListener("DOMContentLoaded", function (e) {
  console.log("HTML parsed and DOM tree built!", e);
});
//parsing will start from top to bottom
//doesnt wait for images , css and fonts ...
//if script tag is placed inside the header
//will pause parsing to load the script and starts executing it
//this maybe a problem;working with DOM tree when its not ready yet
//best practice to put it at the end of body tag
//at that moment DOM tree is ready.
//async scripts don't block parsing or DOMContentLoaded
//DOMContentLoaded event will still be fired even if script at end of body

//if you need to wait for everything ?
window.addEventListener("load", function () {
  console.log("Everything is fully loaded");
});

//before leaving page event
window.addEventListener("beforeunload", function (e) {
  e.preventDefault();
  e.returnValue = "";
});

//different ways of loading JS in HTML
const regular = `<script src="script.js"></script>`;
//inside head :
//1-Parsing HTML /2-reaches script element ->pauses:fetch script + execut 3/finish parsing HTML
//4-DOMContentLoaded event is fired
//body end
//1-parsing HTML /2-fetch script + execut /3-DOMContentLoaded event is fired
//still not perfect:JS could have been loaded before

const async = `<script async src="script.js"></script>`;
//inside head
//1-1-parsing HTML and fetch script in parallel //2- pauses to execut 3-finish parsing
//4-DOMContentLoaded event is fired

const defer = `<script defer src="script.js"></script>`;
//inside head
//1-1-parsing HTML and fetch script in parallel //2-execute when finished parsing
//3-DOMContentLoaded event is fired

//async and defer at body end dont make sense
//if many async -> order of execution of scripts may not be respected
//arrive first -> execute first

//defer respects the order
